### ISSUE TITLE
Deprecation of 'set-env' in GH actions

### ISSUE THREAD

**Issue by mammo0** [c-py/action-dotenv-to-setenv#1]
Hello,

the use of `set-env` in GH actions is now deprecated:

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Now an environment variable can be set with:
```shell
echo "VARIABLE=value" >> $GITHUB_ENV
```

In the following steps the variable can be used with: `{{ env.VARIABLE }}`, just like before.

**Comment by c-py** [comment]
@mammo0 Thank you for the contribution!
