### ISSUE TITLE
Syntax Error when special Characters are in the .env file

### ISSUE THREAD

**Issue by jschiefner** [c-py/action-dotenv-to-setenv#3]
In our project we have an environment variable where there are `(...)` parantheses in the value. This causes the github action to fail with a `syntax error` in `entrypoint.sh`: `unexpected character on line 1: "("`.

This can be circumvented by surrounding the environment variable value with `"..."` double or single quotes, maybe this could be suggested in the README of this repo or somehow the syntax error could be fixed.

**Comment by c-py** [comment]
@jschiefner Thanks for the raising this issue. Apologies for the delay getting back to you.


I have pushed a [release to resolve this](https://github.com/c-py/action-dotenv-to-setenv/releases/tag/v3), implementing your suggestion to wrap the environment variable in double quotes.

I have also opened a [PR with the upstream project](https://github.com/madcoda/dotenv-shell/pull/10) which this action is based on.

Cheers

**Comment by jschiefner** [comment]
@c-py Thanks a lot! 🙏🏼
